### ISSUE TITLE
remove legacy fact and make puppet 8 happy

### ISSUE THREAD

**Issue by maxadamo** [saz/puppet-vim#30]
the fact `@osfamily` no longer works with puppet-8
It should be changed to `@os['family']`

**Comment by maxadamo** [comment]
💡 @saz, my 2 cents, perhaps your modules should not be publicly available if you are not willing to handle PRs in a timely manner. Puppet 8 is out from quite some time now.

**Comment by saz** [comment]
Feel free to stop using my modules. I'm working on them in my spare time without getting paid. If you can do better, go ahead and release your own modules.

Besides that, I also might forget about things or miss them.

**Comment by maxadamo** [comment]
I knew it wouldn't be polite from my side and I really want to apologize. 
I also know that this is something that we're all doing in our spare time. 
But at same time, if a module is on Forge, and it's also on GitHuib, you set some expectations. 
Again, my apologies for being tough, but I was hoping to disable legacy facts on puppet at some point.

**Comment by saz** [comment]
I'm always happy about a friendly reminder. As said, I might miss things or forget about them.

I'll have a look at it today or tomorrow and create a new release.
